"""Generate structured JSON and PDF reports from scan findings."""

# src/reports/generator.py
"""
Report Generator: JSON (machine-readable) + PDF (human-readable)
Uses WeasyPrint for HTML→PDF conversion [[17]]
"""
import json
import logging
from pathlib import Path
from datetime import datetime
from pydantic import BaseModel

try:
    from weasyprint import HTML, CSS  # pip install weasyprint
except ModuleNotFoundError:  # pragma: no cover
    HTML = None
    CSS = None

class ReportData(BaseModel):
    """Structured report content"""
    engagement_id: str
    timestamp: str
    target: str
    findings: list[dict]
    ai_recommendations: list[dict]
    remediation_plan: dict  # {short_term: [...], long_term: [...]}

class ReportGenerator:
    def __init__(self, output_dir: Path = Path("reports")):
        self.output_dir = output_dir
        self.output_dir.mkdir(parents=True, exist_ok=True)
        self.logger = logging.getLogger(__name__)
    
    def save_json(self, data: ReportData, filename: str | None = None) -> Path:
        """Save machine-readable JSON report"""
        filename = filename or f"report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
        path = self.output_dir / filename
        with open(path, "w", encoding="utf-8") as f:
            json.dump(data.model_dump(), f, indent=2, default=str)
        return path
    
    def save_pdf(self, data: ReportData, filename: str | None = None) -> Path:
        """Generate human-readable PDF from HTML template.

        Falls back to HTML output when WeasyPrint is unavailable.
        """
        use_html_fallback = HTML is None or CSS is None
        extension = "html" if use_html_fallback else "pdf"
        filename = filename or f"report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.{extension}"
        path = self.output_dir / filename
        
        # Simple HTML template (expand this as you learn CSS)
        html_content = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="utf-8">
            <style>
                body {{ font-family: Arial, sans-serif; margin: 2cm; line-height: 1.5; }}
                .header {{ border-bottom: 2px solid #333; padding-bottom: 1cm; }}
                .finding {{ margin: 1cm 0; padding: 0.5cm; border-left: 4px solid #e74c3c; }}
                .remediation {{ background: #f8f9fa; padding: 0.5cm; margin: 0.5cm 0; }}
                .short-term {{ border-left: 4px solid #f39c12; }}
                .long-term {{ border-left: 4px solid #3498db; }}
                table {{ width: 100%; border-collapse: collapse; margin: 0.5cm 0; }}
                th, td {{ border: 1px solid #ddd; padding: 8px; text-align: left; }}
                th {{ background: #f2f2f2; }}
            </style>
        </head>
        <body>
            <div class="header">
                <h1>Security Assessment Report</h1>
                <p><strong>Engagement ID:</strong> {data.engagement_id}</p>
                <p><strong>Target:</strong> {data.target}</p>
                <p><strong>Generated:</strong> {data.timestamp}</p>
            </div>
            
            <h2>Executive Summary</h2>
            <p>Scan completed on {data.target}. Found {len(data.findings)} potential issues.</p>
            
            <h2>Findings</h2>
            {''.join(f'''
            <div class="finding">
                <h3>{f.get("title", "Finding")}</h3>
                <p><strong>MITRE:</strong> {f.get("mitre", "N/A")}</p>
                <p>{f.get("description", "")}</p>
            </div>
            ''' for f in data.findings)}
            
            <h2>AI Recommendations</h2>
            {''.join(f'''
            <div class="finding">
                <h3>{r.get("finding_summary", "")}</h3>
                <p><strong>Technique:</strong> {r.get("mitre_technique", "")} | 
                   <strong>Risk:</strong> {r.get("risk_level", "")} | 
                   <strong>Confidence:</strong> {r.get("confidence", 0)*100:.0f}%</p>
                <p><em>Suggestion (human-executed only):</em> {r.get("attack_suggestion", "")}</p>
            </div>
            ''' for r in data.ai_recommendations)}
            
            <h2>Remediation Plan</h2>
            <div class="remediation short-term">
                <h3>🔧 Short-Term Fixes (Immediate)</h3>
                <ul>
                    {''.join(f"<li>{fix}</li>" for fix in data.remediation_plan.get("short_term", []))}
                </ul>
            </div>
            <div class="remediation long-term">
                <h3>🏗️ Long-Term Improvements (Strategic)</h3>
                <ul>
                    {''.join(f"<li>{fix}</li>" for fix in data.remediation_plan.get("long_term", []))}
                </ul>
            </div>
            
            <hr>
            <p><small>Generated by Sharingan v0.1 • Human review required before action</small></p>
        </body>
        </html>
        """
        
        if use_html_fallback:
            path.write_text(html_content, encoding="utf-8")
            self.logger.warning("weasyprint_missing: report_path=%s", str(path))
            return path

        # Convert HTML to PDF
        assert HTML is not None and CSS is not None
        HTML(string=html_content).write_pdf(
            path,
            stylesheets=[CSS(string="""
                @page { size: A4; margin: 1cm; }
                img { max-width: 100%; }
            """)]
        )
        return path
    
    def generate_full_report(self, data: ReportData) -> tuple[Path, Path]:
        """Generate both JSON and PDF reports"""
        json_path = self.save_json(data)
        pdf_path = self.save_pdf(data)
        self.logger.info("reports_generated", extra={"json": str(json_path), "pdf": str(pdf_path)})
        return json_path, pdf_path